[package]
name = "space"
version = "0.8.2"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "A library providing abstractions for spatial datastructures and search"
documentation = "https://docs.rs/space/"
repository = "https://github.com/rust-cv/space"
keywords = ["space", "knn", "ann", "search"]
categories = ["no-std", "computer-vision", "data-structures"]
license = "MIT"
readme = "README.md"

[dependencies]
serde = { version = "1.0.104", features = ["derive"], optional = true }

[features]
simd = []