[package]
name = "space"
version = "0.8.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "A library providing abstractions for spatial datastructures and search"
documentation = "https://docs.rs/space/"
repository = "https://github.com/vadixidav/space"
keywords = ["space", "knn", "ann", "search"]
license = "MIT"
readme = "README.md"

[dependencies]
