[package]
name = "space"
version = "0.8.4"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "A library providing abstractions for spatial datastructures and search"
documentation = "https://docs.rs/space/"
repository = "https://github.com/rust-cv/space"
keywords = ["space", "knn", "ann", "search"]
categories = ["no-std", "computer-vision", "data-structures"]
license = "MIT"
readme = "README.md"

[features]
simd = ["packed_simd"]
# Turns on liballoc, but doesn't itself implement anything
alloc = []
# Implements hamming distance for Vec
hamming-vec = ["alloc"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
packed_simd = { version = "0.3.3", optional = true }

[dev-dependencies]
criterion = "0.3.1"
rand_core = "0.5.1"
rand_pcg = "0.2.1"

[[bench]]
name = "knn"
harness = false
